# Generated by Django 5.2.4 on 2025-07-17 00:41

from django.db import migrations

def create_user_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group_name in ['manager', 'delivery-crew']:
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ("restaurantAPI", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_user_group),
    ]