# Generated by Django 5.2.4 on 2025-07-19 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantAPI", "0002_create_manage_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
